export interface TermOption {
  label: string
  value: string
  note?: string
}

export const roleIncludeTerms: TermOption[] = [
  { label: 'Engineer', value: 'engineer', note: 'widest' },
  { label: 'Developer', value: 'developer' },
  { label: 'Software', value: 'software' },
  { label: 'SDE', value: 'sde' },
  { label: 'SWE', value: 'swe' },
  { label: 'SSE', value: 'sse', note: 'also hits "assessment"' },
  { label: 'Software Engineer', value: 'software engineer' },
  { label: 'Software Developer', value: 'software developer' },
  { label: 'Software Development', value: 'software development' },
  { label: 'Member of Technical Staff', value: 'member of technical staff' },
  { label: 'Member, Tech', value: 'member, tech', note: 'Oracle/Salesforce style' },
  { label: 'Senior Member, Tech', value: 'senior member, tech' },
  { label: 'MTS', value: 'mts' },
  { label: 'AMTS', value: 'amts' },
  { label: 'Architect', value: 'architect' },
  { label: 'Computer Scientist', value: 'computer scientist', note: 'Adobe et al.' },
  { label: 'Backend', value: 'backend' },
  { label: 'Back end', value: 'back end' },
  { label: 'Full stack', value: 'full stack' },
  { label: 'Platform', value: 'platform' },
  { label: 'Infrastructure', value: 'infrastructure' },
  { label: 'Distributed', value: 'distributed' },
  { label: 'Microservice', value: 'microservice' },
  { label: 'API', value: 'api' },
  { label: 'Java', value: 'java' },
  { label: 'Python', value: 'python' },
  { label: 'Golang', value: 'golang' },
  { label: 'Data engineer', value: 'data engineer' },
  { label: 'Data scientist', value: 'data scientist' },
  { label: 'Machine learning', value: 'machine learning' },
  { label: 'SRE', value: 'sre' },
  { label: 'Site reliability', value: 'site reliability' },
  { label: 'DevOps', value: 'devops' },
  { label: 'Cloud', value: 'cloud' },
  { label: 'Security', value: 'security' },
  { label: 'Mobile', value: 'mobile' },
  { label: 'Android', value: 'android' },
  { label: 'iOS', value: 'ios' },
  { label: 'Frontend', value: 'frontend' },
  { label: 'Front end', value: 'front end' },
]

/** Beats the include list (see `BoardFilter`). */
export const roleExcludeTerms: TermOption[] = [
  { label: 'Manager', value: 'manager', note: 'biggest single win' },
  { label: 'Director', value: 'director' },
  { label: 'Vice President', value: 'vice president' },
  { label: 'Head of', value: 'head of' },
  { label: 'Intern', value: 'intern' },
  { label: 'Sales', value: 'sales' },
  { label: 'Account Executive', value: 'account executive' },
  { label: 'Marketing', value: 'marketing' },
  { label: 'Recruiter', value: 'recruit' },
  { label: 'Support', value: 'support' },
  { label: 'Customer Success', value: 'customer success' },
  { label: 'Finance', value: 'finance' },
  { label: 'Legal', value: 'legal' },
  { label: 'Operations', value: 'operations' },
  { label: 'Specialist', value: 'specialist' },
  { label: 'Analyst', value: 'analyst' },
  { label: 'Consultant', value: 'consultant' },
  { label: 'Principal', value: 'principal', note: 'if targeting IC levels' },
  { label: 'Staff', value: 'staff' },
]
